export const APP_WRITE_ID = '661697d6d32f7dfede71'
export const DB_ID = 'markets-base'
export const COLLECTION_TARIFFS = 'tariffs'
export const COLLECTION_FAQ_ID = 'faq'
export const COLLECTION_USERS = 'users'
export const STORAGE_ID = 'storage'
